-- 创建序列（如果不存在）
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM all_sequences WHERE sequence_owner = 'ADMIN1' AND sequence_name = 'SEQ_T_BORROW';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ADMIN1.SEQ_T_BORROW INCREMENT BY 1 START WITH 102 NOMAXVALUE NOCYCLE NOCACHE';
  END IF;
END;
/

-- 删除原有触发器（如果存在）
BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER ADMIN1.t_borrow_trig';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4080 THEN  -- ORA-04080: 触发器不存在
      RAISE;
    END IF;
END;
/

-- 重新创建触发器
CREATE OR REPLACE TRIGGER ADMIN1.t_borrow_trig
BEFORE INSERT ON ADMIN1.T_BORROW
REFERENCING OLD AS "OLD" NEW AS "NEW"
FOR EACH ROW
BEGIN
  SELECT ADMIN1.SEQ_T_BORROW.NEXTVAL INTO :NEW.BORROWID FROM DUAL;
END;
/ 